### PR TITLE
Adds support for CallPermit and Randomness precompiles in Moonbeam and Moonriver

### PR DESCRIPTION
**Pull request by eshaben**
### Description/Original PRs

Adds support for CallPermit and Randomness precompiles in Moonbeam and Moonriver. 

The randomness page update will be applied in the randomness PR

### CODE REVIEW

**Review by albertov19 — CHANGES_REQUESTED** [review]
I think you missed to update the "tabbed" Network thing in the `randomness.md` file, right?

**Comment by eshaben** [comment]
> I think you missed to update the "tabbed" Network thing in the `randomness.md` file, right?

It's getting added in the randomness PR since that page hasn't been merged yet

**Comment by eshaben** [comment]
https://github.com/PureStake/moonbeam-docs-cn/pull/152

**Review by albertov19 — APPROVED** [review]
LGTM

**Pull request merged**
